ALTER TABLE "Room"
ADD COLUMN "nightly_variable_cost" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "breakfast_cost" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "lunch_cost" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "dinner_cost" INTEGER NOT NULL DEFAULT 0;

